---
- name: Validate SMTP Configuration for PX-Backup Receiver
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/receiver/validate_smtp.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - smtp_configs is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"

    - name: Validate SMTP configurations
      block:
        - name: Validate SMTP settings
          receiver:
            operation: VALIDATE_SMTP
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            org_id: "{{ org_id | default('default') }}"
            receiver_type: "EMAIL"
            email_config:
              from_address: "{{ item.email_config.from_address }}"
              host: "{{ item.email_config.host }}"
              port: "{{ item.email_config.port }}"
              encryption_ssl: "{{ item.email_config.encryption_ssl | default(false) }}"
              encryption_starttls: "{{ item.email_config.encryption_starttls | default(false) }}"
              authentication: "{{ item.email_config.authentication | default(false) }}"
              auth_username: "{{ item.email_config.auth_username | default(omit) }}"
              auth_password: "{{ item.email_config.auth_password | default(omit) }}"
            validate_certs: "{{ item.validate_certs | default(true) }}"
            recipient_id: "{{ item.recipient_id | default([]) }}"
          loop: "{{ smtp_configs }}"
          register: validate_result
          loop_control:
            label: "{{ item.name }}"


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ validate_result }}"
        output_filename_prefix: "receiver_validate_smtp"
      when: output_config.enabled | default(false)