---
# Define Cloud Credential list
cloud_credentials:
  # AWS Configuration
  - name: "aws-cc"
    credential_type: "AWS"
    aws_config:
      access_key: "access_key"
      secret_key: "secret_key"

  # GCP Configuration  
  - name: "gcp-cc"
    credential_type: "Google"
    google_config:
      project_id: "my-project-id"
      json_key: |
        {
          "type": "service_account",
          "project_id": "my-project-id",
          "private_key_id": "abcd1234...",
          "private_key": "-----BEGIN PRIVATE KEY-----\nYourPrivateKey\n-----END PRIVATE KEY-----\n",
          "client_email": "service-account@project.iam.gserviceaccount.com",
          "client_id": "123456789",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/service-account%40project.iam.gserviceaccount.com"
        }

  # IBM Configuration
  - name: "ibm-cc"
    credential_type: "IBM"
    ibm_config:
      api_key: "mystorageaccount"

  # Rancher Configuration
  - name: "rancher-cc"
    credential_type: "Rancher"
    rancher_config:
      endpoint: "rancher-endpoint"
      token: "rancher-token"

  # Azure Configuration
  - name: "azure-cc"
    credential_type: "Azure"
    azure_config:
      account_name: "mystorageaccount"
      account_key: "your-azure-storage-account-key"
      client_secret: "your-azure-client-secret"
      client_id: "your-azure-client-id"
      tenant_id: "your-azure-tenant-id"
      subscription_id: "your-azure-subscription-id"