---
- name: Configure PX-Backup Roles
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/role/create.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - roles is defined
          - roles | length > 0
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Create roles
      block:
        - name: Debug payload
          debug:
            var: item
          loop: "{{ roles }}"
        - name: Create role
          role:
            operation: CREATE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            org_id: "{{ org_id | default('default') }}"
            labels: "{{ item.labels | default(omit) }}"
            rules: "{{ item.rules }}"
            # SSL Certificate Parameters
            validate_certs: "{{ px_backup_validate_certs | default(true) }}"
            ca_cert: "{{ px_backup_ca_cert | default(omit) }}"
            client_cert: "{{ px_backup_client_cert | default(omit) }}"
            client_key: "{{ px_backup_client_key | default(omit) }}"
          loop: "{{ roles }}"
          register: role_result
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to create role: {{ role_result.results | selectattr('failed', 'true') | map(attribute='msg') | list }}"
          when: role_result is defined and role_result.results is defined

        - name: Fail with error message
          fail:
            msg: "Failed to create roles. See above for details."


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ role_result }}"
        output_filename_prefix: "role_create"
      when: output_config.enabled | default(false)