---
# Backup locations to inspect
backup_locations_inspect:
  - name: "bl-sync-target"
    include_secrets: true

  - name: "azure"
    include_secrets: true

# Global inspect configuration
default_include_secrets: true