---
- name: Get Current User Details from Token
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"

    - name: Decode JWT token to get user info
      block:
        - name: Extract token payload (base64 decode)
          set_fact:
            # JWT tokens have 3 parts separated by dots: header.payload.signature
            # We want the payload (middle part) which contains user info
            token_payload_b64: "{{ px_backup_token.split('.')[1] }}"

        - name: Add padding to base64 if needed
          set_fact:
            # Base64 strings need to be multiples of 4 characters
            token_payload_padded: "{{ token_payload_b64 + '=' * (4 - (token_payload_b64|length % 4)) if (token_payload_b64|length % 4) != 0 else token_payload_b64 }}"

        - name: Decode base64 payload
          set_fact:
            token_payload_json: "{{ token_payload_padded | b64decode }}"

        - name: Parse JSON payload
          set_fact:
            current_user_info: "{{ token_payload_json | from_json }}"

        - name: Display current user information
          debug:
            msg:
              - "Current User Email: {{ current_user_info.email | default('Not available') }}"
              - "User Subject (ID): {{ current_user_info.sub | default('Not available') }}"
              - "Issuer: {{ current_user_info.iss | default('Not available') }}"
              - "Token Issued At: {{ current_user_info.iat | default('Not available') }}"
              - "Token Expires At: {{ current_user_info.exp | default('Not available') }}"
              - "Audience: {{ current_user_info.aud | default('Not available') }}"
              - "JWT ID: {{ current_user_info.jti | default('Not available') }}"

        - name: Extract user ID for role queries
          set_fact:
            current_user_id: "{{ current_user_info.sub | default('') }}"

      rescue:
        - name: Display token decode error
          debug:
            msg: "Failed to decode JWT token. Token might be malformed or encrypted."

    - name: Get roles owned by current user
      block:
        - name: Get all roles
          role:
            operation: INSPECT_ALL
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id | default('default') }}"
            ssl_config: "{{ ssl_config.px_backup | default({}) }}"
          register: all_roles_result

        - name: Filter roles owned by current user
          set_fact:
            user_owned_roles: "{{ all_roles_result.roles | selectattr('metadata.ownership.owner', 'equalto', current_user_id) | list }}"

        - name: Display user's roles
          debug:
            msg:
              - "Total roles owned by current user: {{ user_owned_roles | length }}"
              - "Role names: {{ user_owned_roles | map(attribute='metadata.name') | list }}"

        - name: Display detailed role information
          debug:
            var: user_owned_roles
          when: user_owned_roles | length > 0

      rescue:
        - name: Display role query error
          debug:
            msg: "Failed to query user roles: {{ all_roles_result.msg if all_roles_result.msg is defined else 'Unknown error' }}"

      when: current_user_id is defined and current_user_id != ""
