---
- name: Update PX-Backup Schedule Policy ownership
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/schedule_policy/update_ownership.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - schedule_policy_ownership_updates is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Update schedule policies ownership
      block:
        - name: Update schedule policy ownership
          schedule_policy:
            operation: UPDATE_OWNERSHIP
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id | default('default') }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            ownership: "{{ item.ownership }}"
          loop: "{{ schedule_policy_ownership_updates }}"
          register: ownership_result
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to update ownership: {{ ownership_result.results | selectattr('failed', 'true') | map(attribute='msg') | list }}"
          when: ownership_result is defined and ownership_result.results is defined

        - name: Fail with error message
          fail:
            msg: "Failed to update schedule policy ownership. See above for details."

    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ ownership_result }}"
        output_filename_prefix: "schedule_policy_update_ownership"
      when: output_config.enabled | default(false)