---
- name: Delete Cluster Example (Idempotent)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure a cluster is absent (deletes if exists)
      purepx.px_backup.cluster:
        state: absent
        api_url: "https://px-backup.example.com"
        token: "{{ px_backup_token }}"
        name: "my-old-cluster"
        org_id: "default"
        # NOTE: The 'cluster' module requires 'kubeconfig' or 'px_config' even for
        # the 'absent' state. A dummy value can be provided if the real one isn't available.
        kubeconfig: "dummy-value"

