---
- name: List all PX-Backup clusters
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir}}/group_vars/common/all.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
        fail_msg: "Required variables px_backup_api_url and px_backup_token must be defined"

  tasks:
    - name: Fetch bearer token from auth module
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Cluster Enumerate call
      cluster:
        operation: INSPECT_ALL
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        org_id: "{{ org_id | default('default') }}"
