---
- name: Inspect PX-Backup Clusters
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/cluster/inspect.yaml"

  pre_tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Debug variables
      debug:
        msg:
          - "API URL: {{ px_backup_api_url }}"
          - "Total clusters to inspect: {{ clusters_inspect | length }}"

    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - clusters_inspect is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Inspect clusters
      block:
        - name: Get cluster details
          cluster:
            operation: INSPECT_ONE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid | default(omit) }}"
            org_id: "{{ org_id | default('default') }}"
            include_secrets: "{{ item.include_secrets | default(default_include_secrets) }}"
            # SSL Certificate Parameters
            ssl_config: "{{ ssl_config.px_backup | default({}) }}"
          register: inspect_result
          loop: "{{ clusters_inspect }}"
          loop_control:
            label: "{{ item.name }}"

        - name: Log failure details
          debug:
            msg: |
              Failed during cluster inspection process.

              {% if ansible_failed_task is defined %}
              Failed task: {{ ansible_failed_task.name }}
              Failed result: {{ ansible_failed_result }}
              {% endif %}

              {% if inspect_result is defined %}
              Inspection failures: {{ inspect_result.results | selectattr('failed', 'true') | map(attribute='msg') | list }}
              {% endif %}

              Clusters attempted: {{ clusters_inspect | map(attribute='name') | list }}

        - name: Show detailed error information
          debug:
            var: ansible_failed_result
          when: ansible_failed_result is defined

        - name: Fail with error message
          fail:
            msg: "Error during cluster inspection process. Check the failure logs above."

    - name: Show inspection results
      debug:
        msg:
          - "Inspection Results:"
          - "----------------------------------------"
          - "Cluster: {{ item.item.name }}"
          - "UID: {{ item.item.uid }}"
          - "Status: {{ 'Success' if not item.failed else 'Failed' }}"
          - "Include Secrets: {{ item.item.include_secrets | default(false) }}"
          - "----------------------------------------"
      loop: "{{ inspect_result.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      when: inspect_result is defined

    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ inspect_result }}"
        output_filename_prefix: "cluster_inspect"
      when:
        - output_config.enabled | default(false)
        - inspect_result is defined