---
- name: Inspect PX-Backup Clusters
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/cluster/inspect.yaml"

  pre_tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Debug variables
      debug:
        msg:
          - "API URL: {{ px_backup_api_url }}"
          - "Total clusters to inspect: {{ clusters_inspect | length }}"

    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - clusters_inspect is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Inspect clusters
      block:
        - name: Get cluster details
          cluster:
            operation: INSPECT_ONE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            org_id: "{{ org_id | default('default') }}"
            include_secrets: "{{ item.include_secrets | default(default_include_secrets) }}"
            # SSL Certificate Parameters
            validate_certs: "{{ px_backup_validate_certs | default(true) }}"
            ca_cert: "{{ px_backup_ca_cert | default(omit) }}"
            client_cert: "{{ px_backup_client_cert | default(omit) }}"
            client_key: "{{ px_backup_client_key | default(omit) }}"
          register: inspect_result
          loop: "{{ clusters_inspect }}"
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to inspect clusters: {{ inspect_result.results | selectattr('failed', 'true') | map(attribute='msg') | list }}"
          when: inspect_result is defined and inspect_result.results is defined

        - name: Fail with error message
          fail:
            msg: "Failed to inspect clusters. See above for details."


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ inspect_result }}"
        output_filename_prefix: "cluster_inspect"
      when: output_config.enabled | default(false)
