---
- name: Share PX-Backup Cluster
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Fetch bearer token from auth module
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Share cluster with users and groups
      cluster:
        operation: SHARE_CLUSTER
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        org_id: "default"
        name: "test-cluster"
        uid: "feb239d3-4af4-4b2e-b010-cc8f4f2e254c"
        cluster_share:
          users:
            - "user1"
          groups: []
          share_cluster_backups: true