---
- name: Share PX-Backup Clusters
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/cluster/share.yaml"

  tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - clusters_share is defined
        fail_msg: "Required variables must be defined: px_backup_api_url, px_backup_token, and clusters_share"
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Share PX-Backup clusters with users and groups
      cluster:
        operation: SHARE_CLUSTER
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        org_id: "{{ item.org_id | default('default') }}"
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        cluster_share: "{{ item.cluster_share }}"
        # SSL Certificate Parameters
        validate_certs: "{{ px_backup_validate_certs | default(true) }}"
        ca_cert: "{{ px_backup_ca_cert | default(omit) }}"
        client_cert: "{{ px_backup_client_cert | default(omit) }}"
        client_key: "{{ px_backup_client_key | default(omit) }}"
      loop: "{{ clusters_share }}"
      loop_control:
        label: "{{ item.name }}"
      register: share_result


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ share_result }}"
        output_filename_prefix: "cluster_share"
      when: output_config.enabled | default(false)
