---
- name: Unshare PX-Backup Clusters
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/cluster/unshare.yaml"

  tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - clusters_unshare is defined
        fail_msg: "Required variables must be defined: px_backup_api_url, px_backup_token, and clusters_unshare"
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Unshare PX-Backup clusters with users and groups
      cluster:
        operation: UNSHARE_CLUSTER
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        org_id: "{{ item.org_id | default('default') }}"
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        cluster_share: "{{ item.cluster_share }}"
      loop: "{{ clusters_unshare }}"
      loop_control:
        label: "{{ item.name }}"
