---
- name: Update PX-Backup backup share settings
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/cluster/update_ownership.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - backup_share_updates is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Update backup shares for clusters
      block:
        - name: Process backup share updates
          cluster:
            operation: UPDATE_BACKUP_SHARE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id | default('default') }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            add_backup_share: "{{ item.add_backup_share | default(omit) }}"
            del_backup_share: "{{ item.del_backup_share | default(omit) }}"
            # SSL Certificate Parameters
            ssl_config: "{{ ssl_config.px_backup | default({}) }}"
          loop: "{{ backup_share_updates }}"
          register: backup_share_results
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: Log failure details
          debug:
            msg: "Failed to update backup shares: {{ backup_share_results.results | selectattr('failed', 'true') | map(attribute='msg') | list }}"

        - name: Fail on errors
          fail:
            msg: "Error updating backup shares. See debug output for details."


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ backup_share_results }}"
        output_filename_prefix: "cluster_update_ownership"
      when: output_config.enabled | default(false)