---
- name: Configure Keycloak Roles
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/keycloak_role/create.yaml"

  tasks:
    - name: Login and fetch Keycloak token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Create Keycloak Role
      block:
        - name: Create Keycloak Role
          keycloak_role:
            operation: CREATE
            auth_url: "{{ pxcentral_auth_url }}"
            token: "{{ keycloak_token }}"
            name: "{{ item.name }}"
            description: "{{ item.description | default(omit) }}"
            attributes: "{{ item.attributes | default(omit) }}"
            # SSL Certificate Parameters
            ssl_config: "{{ ssl_config.px_central | default({}) }}"
          loop: "{{ keycloak_roles }}"
          register: create_result
          loop_control:
            label: "{{ item.name }}"


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ create_result }}"
        output_filename_prefix: "keycloak_role_create"
      when: output_config.enabled | default(false)
