---
- name: Enumerate Keycloak Roles Example
  hosts: keycloak_role
  gather_facts: false
  vars:
    # Pagination settings from group_vars - uses default pagination
    # Override with specific pagination config if needed
    current_pagination: "{{ pagination }}"

    # Alternative pagination configurations:
    # current_pagination: "{{ pagination_configs.small_batch }}"  # 10 roles
    # current_pagination: "{{ pagination_configs.large_batch }}"  # 50 roles
    # current_pagination: "{{ pagination_configs.all_roles }}"    # 1000 roles

  tasks:
    - name: Validate required variables
      assert:
        that:
          - pxcentral_auth_url is defined
          - pxcentral_client_id is defined
          - pxcentral_username is defined
          - pxcentral_password is defined
          - current_pagination is defined
        fail_msg: "Required variables must be defined. Check group_vars/common/all.yaml and group_vars/keycloak_role/enumerate.yaml"

    - name: Get authentication token
      auth:
        auth_url: "{{ pxcentral_auth_url }}"
        client_id: "{{ pxcentral_client_id }}"
        username: "{{ pxcentral_username }}"
        password: "{{ pxcentral_password }}"
        token_duration: "{{ token_duration | default('1h') }}"
        ssl_config: "{{ ssl_config.px_central | default({}) }}"
      register: auth_result
      no_log: false

    - name: Set token fact
      set_fact:
        keycloak_token: "{{ auth_result.access_token }}"
      no_log: false

    - name: Enumerate all Keycloak roles
      keycloak_role:
        operation: ENUMERATE
        auth_url: "{{ pxcentral_auth_url }}"
        token: "{{ keycloak_token }}"
        first: "{{ current_pagination.first }}"
        max: "{{ current_pagination.max }}"
        ssl_config: "{{ ssl_config.px_central | default({}) }}"
      register: roles_list

    - name: Display roles count
      debug:
        msg: "Found {{ roles_list.roles | length }} roles (showing {{ current_pagination.first }} to {{ current_pagination.first + current_pagination.max }})"

    - name: Display role summary
      debug:
        msg: "Role: {{ item.name }} - {{ item.description | default('No description') }}"
      loop: "{{ roles_list.roles }}"
      loop_control:
        label: "{{ item.name }}"
      when: display_options.show_descriptions | default(true)

    - name: Display roles with custom attributes
      debug:
        msg: "Role '{{ item.name }}' has custom attributes: {{ item.attributes | default({}) }}"
      loop: "{{ roles_list.roles }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - display_options.show_attributes | default(true)
        - item.attributes is defined
        - item.attributes | length > 0

    - name: "Filter roles by custom criteria (example: roles with 'px-backup' service)"
      set_fact:
        px_backup_roles: "{{ roles_list.roles | selectattr('attributes.service', 'defined') | selectattr('attributes.service', 'contains', 'px-backup') | list }}"

    - name: Display PX-Backup related roles
      debug:
        msg: "PX-Backup role: {{ item.name }} - Access Level: {{ item.attributes.access_level | default(['N/A']) | first }}"
      loop: "{{ px_backup_roles }}"
      loop_control:
        label: "{{ item.name }}"
      when: px_backup_roles | length > 0

    - name: Show pagination info
      debug:
        msg: |
          Pagination Information:
          - Requested: {{ current_pagination.first }} to {{ current_pagination.first + current_pagination.max }}
          - Returned: {{ roles_list.roles | length }} roles
          - To get next page, set first: {{ current_pagination.first + current_pagination.max }}

    - name: Get next page example (if there might be more roles)
      keycloak_role:
        operation: ENUMERATE
        auth_url: "{{ pxcentral_auth_url }}"
        token: "{{ keycloak_token }}"
        first: "{{ current_pagination.first + current_pagination.max }}"
        max: "{{ current_pagination.max }}"
        ssl_config: "{{ ssl_config.px_central | default({}) }}"
      register: next_page_roles
      when: roles_list.roles | length == current_pagination.max

    - name: Display next page info
      debug:
        msg: "Next page contains {{ next_page_roles.roles | length }} additional roles"
      when: next_page_roles is defined and next_page_roles.roles is defined
