---
- name: Update Keycloak Roles
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/keycloak_role/update.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - pxcentral_auth_url is defined
          - keycloak_roles_update is defined
        fail_msg: "Required variables must be defined"

    - name: Get current timestamp
      set_fact:
        current_timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

  tasks:
    - name: Login and fetch Keycloak token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Update roles
      block:
        - name: Update Keycloak roles
          keycloak_role:
            operation: UPDATE
            auth_url: "{{ pxcentral_auth_url }}"
            token: "{{ keycloak_token }}"
            name: "{{ item.name | default(omit) }}"
            description: "{{ item.description | default(omit) }}"
            attributes: "{{ item.attributes | default(omit) }}"
            # SSL Certificate Parameters
            ssl_config: "{{ ssl_config.px_central | default({}) }}"
          register: update_result
          loop: "{{ keycloak_roles_update }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to update Keycloak roles: {{ update_result.results | default([]) | selectattr('failed', 'true') | map(attribute='msg') | list }}"

        - name: Fail with error message
          fail:
            msg: "Failed to update Keycloak roles. See above for details."

    - name: Show update results
      debug:
        msg:
          - "Update Results:"
          - "----------------------------------------"
          - "Role: {{ item.item }}"
          - "Configuration Update: {{ 'Success' if item is changed else 'No changes needed' }}"
          - "----------------------------------------"
      loop: "{{ update_result.results }}"


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ update_result }}"
        output_filename_prefix: "keycloak_role_update"
      when: output_config.enabled | default(false)
