namespace: purepx
name: px_backup
version: 2.8.1
readme: README.md
authors:
- Portworx
description: Collection for managing Portworx Backup application on kubernetes cluster 
license:
- GPL-2.0-or-later
tags: [portworx, px-backup]
documentation: https://docs.portworx.com/portworx-backup-on-prem
repository: https://github.com/portworx/px_backup_module
