---
restore_deletes:
  - name: "restoocp"
    uid: "restore-uid"
    # Optional: cluster_ref if deleting through specific cluster
    # cluster_ref:
    #   name: "prod-cluster"
    #   uid: "cluster-456"
    validate_certs: true

  # - name: "test-backup"
  #   uid: "backup-789"
  #   validate_certs: true