---
# Restore specific parameter
exclude_failed_resource: true

# Pagination parameters
max_objects: 10
object_index: 0

# Filter parameters
name_filter: ""
labels: {}
cluster_name_filter: ""
cluster_uid_filter: ""
include_detailed_resources: false
owners: []
backup_object_type:
  type: "All"
status: []

# Time range filter
time_range:
  start_time: ""
  end_time: ""

# Sort option
sort_option:
  sortBy: "CreationTimestamp"
  sortOrder: "Descending"
