# ansible-collection/inventory/group_vars/backup/inspect.yaml
---
# Required variables
restore_name: "default-restore-with-delete"    # Name of the backup to inspect

# Optional parameters
validate_certs: true              # Whether to validate SSL certificates
debug_output: false               # Enable to see raw backup result structure