# ansible-collection/inventory/group_vars/backup/inspect.yaml
---
# Required variables
restore_name: "res62"    # Name of the backup to inspect
restore_uid: "b9eef5cb-42ee-49f8-9bc0-2488522bf91c"      # UID of the backup to inspect

# Optional parameters
validate_certs: true              # Whether to validate SSL certificates
debug_output: false               # Enable to see raw backup result structure