---
- name: Configure PX-Backup Recipients
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/recipient/create.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - recipients is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"

    - name: Create recipients
      block:
        - name: Create recipient configuration
          recipient:
            operation: CREATE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            org_id: "{{ org_id | default('default') }}"
            recipient_type: "{{ item.recipient_type | default('EMAIL') }}"
            recipient_ids: "{{ item.recipient_ids }}"
            receiver_ref:
              name: "{{ item.receiver_ref.name }}"
              uid: "{{ item.receiver_ref.uid |default(omit) }}"
            severity: "{{ item.severity | default('CRITICAL') }}"
            active: "{{ item.active | default(true) }}"
            # SSL Certificate Parameters
            ssl_config: "{{ ssl_config.px_backup | default({}) }}"
          loop: "{{ recipients }}"
          register: recipient_result
          loop_control:
            label: "{{ item.name }}"


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ recipient_result }}"
        output_filename_prefix: "recipient_create"
      when: output_config.enabled | default(false)