---
- name: Delete PX-Backup Recipients
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/recipient/delete.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - recipients_to_delete is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"

    - name: Delete recipients
      block:
        - name: Delete recipient configuration
          recipient:
            operation: DELETE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            org_id: "{{ org_id | default('default') }}"
            validate_certs: "{{ item.validate_certs | default(true) }}"
          loop: "{{ recipients_to_delete }}"
          register: delete_result
          loop_control:
            label: "{{ item.name }}"


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ delete_result }}"
        output_filename_prefix: "recipient_delete"
      when: output_config.enabled | default(false)