---
- name: List PX-Backup Recipients
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"

    - name: List all recipients
      block:
        - name: Enumerate recipients
          recipient:
            operation: INSPECT_ALL
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id | default('default') }}"
            recipient_type: "{{ recipient_type | default('EMAIL') }}"
            validate_certs: "{{ validate_certs | default(true) }}"
          register: recipient_list


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ recipient_list }}"
        output_filename_prefix: "recipient_enumerate"
      when: output_config.enabled | default(false)