---
# Define Backup Schedule list with all available fields
backup_schedules:
  # Schedule 1: Comprehensive configuration example
  - name: "prod-app-daily-backup"
    owner: "platform-team"
    reclaim_policy: "Retain"
    backup_type: "Normal"
    direct_kdmp: true
    suspend: false
    parallel_backup: true
    keep_cr_status: true
    skip_vm_auto_exec_rules: false
    
    # Namespaces and selectors
    namespaces:
      - "production"
      - "prod-services"
    ns_label_selectors: "environment=production,tier=critical"
    label_selectors:
      app: "ecommerce"
      environment: "production"
      tier: "frontend"
    advanced_resource_label_selector: ""
    
    # Resources configuration
    resource_types:
      - "PersistentVolumeClaim"
      - "ConfigMap"
      - "Secret"
      - "Service"
    exclude_resource_types:
      - "Pod"
      - "ReplicaSet"
    include_resources:
      - name: "prod-db-volume"
        namespace: "production"
        group: ""
        kind: "PersistentVolumeClaim"
        version: "v1"
      - name: "app-config"
        namespace: "production"
        group: ""
        kind: "ConfigMap"
        version: "v1"
    
    # References
    schedule_policy_ref:
      name: "daily-midnight-retain30"
      uid: "a7b8c9d0-e1f2-3456-7890-abcdef123456"
    backup_location_ref:
      name: "aws-s3-primary"
      uid: "b8c9d0e1-f234-5678-9012-bcdef2345678"
    cluster_ref:
      name: "prod-cluster-east"
      uid: "c9d0e1f2-3456-7890-1234-cdef34567890"
    pre_exec_rule_ref:
      name: "database-quiesce"
      uid: "d0e1f234-5678-9012-3456-def456789012"
    post_exec_rule_ref:
      name: "database-unquiesce"
      uid: "e1f23456-7890-1234-5678-ef5678901234"
    volume_resource_only_policy_ref:
      name: "skip-nfs-volumes"
      uid: "f2345678-9012-3456-7890-f67890123456"
    
    # Backup object configuration
    backup_object_type:
      type: "All"
    volume_snapshot_class_mapping:
      "kubernetes.io/aws-ebs": "ebs-snapshot-class"
      "kubernetes.io/gce-pd": "gce-snapshot-class"
    
    # Labels and ownership
    labels:
      team: "platform"
      cost-center: "engineering"
      compliance: "pci-dss"
      backup-tier: "critical"
    ownership:
      owner: "platform-team"
      groups:
        - id: "sre-team"
          access: "Admin"
        - id: "dev-team"
          access: "Read"
      collaborators:
        - id: "john.doe@company.com"
          access: "Write"
        - id: "jane.smith@company.com"
          access: "Read"
      public:
        type: "Read"

  # Schedule 2: VM-specific backup example
  - name: "vm-backup-weekly"
    owner: "vm-admin"
    reclaim_policy: "Delete"
    backup_type: "Generic"
    direct_kdmp: false
    suspend: false
    parallel_backup: false
    keep_cr_status: false
    skip_vm_auto_exec_rules: true
    
    namespaces:
      - "virtual-machines"
    label_selectors:
      vm-type: "production"
      os: "linux"
    
    resource_types:
      - "VirtualMachine"
      - "VirtualMachineInstance"
      - "DataVolume"
    
    schedule_policy_ref:
      name: "weekly-sunday-retain8"
      uid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
    backup_location_ref:
      name: "azure-blob-secondary"
      uid: "b2c3d4e5-f678-9012-bcde-f23456789012"
    cluster_ref:
      name: "vm-cluster-west"
      uid: "c3d4e5f6-7890-1234-cdef-345678901234"
    
    backup_object_type:
      type: "VirtualMachine"
    
    labels:
      backup-type: "vm"
      retention: "weekly"
      
  # Schedule 3: Minimal configuration example
  - name: "test-namespace-backup"
    reclaim_policy: "Delete"
    backup_type: "Normal"
    
    namespaces:
      - "test"
    
    schedule_policy_ref:
      name: "hourly-retain24"
      uid: "d4e5f678-9012-3456-7890-456789012345"
    backup_location_ref:
      name: "minio-local"
      uid: "e5f67890-1234-5678-9012-567890123456"
    cluster_ref:
      name: "test-cluster"
      uid: "f6789012-3456-7890-1234-678901234567"
    
    backup_object_type:
      type: "All"

  # Schedule 4: Advanced filtering example
  - name: "multi-tenant-backup"
    owner: "tenant-admin"
    reclaim_policy: "Retain"
    backup_type: "Normal"
    parallel_backup: true
    
    # Using namespace label selectors instead of explicit namespaces
    ns_label_selectors: "tenant in (acme-corp,globex-inc),backup-enabled=true"
    
    # Complex label selector
    advanced_resource_label_selector: |
      app in (frontend,backend,database),
      tenant=acme-corp,
      backup-priority in (high,critical),
      environment!=development
    
    resource_types:
      - "Deployment"
      - "StatefulSet"
      - "Service"
      - "PersistentVolumeClaim"
      - "ConfigMap"
      - "Secret"
    exclude_resource_types:
      - "Event"
      - "Endpoints"
    
    schedule_policy_ref:
      name: "6hour-retain7days"
      uid: "a9b8c7d6-e5f4-3210-fedc-ba0987654321"
    backup_location_ref:
      name: "gcp-storage-multiregion"
      uid: "b0c9d8e7-f6a5-4321-0fed-cb1098765432"
    cluster_ref:
      name: "multi-tenant-prod"
      uid: "c1d0e9f8-a7b6-5432-10fe-dc2109876543"
    
    backup_object_type:
      type: "All"
    
    labels:
      purpose: "multi-tenant"
      backup-window: "off-peak"
      sla: "premium"
    
    ownership:
      owner: "tenant-admin"
      groups:
        - id: "tenant-operators"
          access: "Write"
        - id: "tenant-viewers"
          access: "Read"