---
backup_schedules:
  - name: "nfs-attached-schedule-demo"
    owner: "admin"
    reclaim_policy: "Delete"  # Options: Invalid, Delete, Retain
    namespaces:
      - "demo-nfs-attached"
    schedule_policy_ref: 
      name: "15min-retain3-incr2"
      uid: "afd10698-97aa-4e43-be69-c4610e51105e"
    backup_location_ref:
      name: "minio"
      uid: "4637d42d-28d9-441d-8dc9-81edbed5b084"
    backup_type: "Normal"
    cluster_ref:
      name: "self"
      uid: "460bdeb4-1bc3-47ec-86db-e1f0b1d52936"
    backup_object_type:
      type: "All"
