---
# Backup schedule enumerate parameters (flat structure)

# Pagination parameters
max_objects: 10
object_index: 0

# Filter parameters
name_filter: ""
labels: {}
cluster_name_filter: "one"
cluster_uid_filter: ""
include_detailed_resources: false
backup_object_type:
  type: "All"
owners: []
status: []

# Time range filter
time_range:
  start_time: ""
  end_time: ""

# Sort option
sort_option:
  sortBy: "CreationTimestamp"
  sortOrder: "Descending"