---
- name: Inspect PX-Backup Rules
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/rule/inspect.yaml"

  pre_tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Debug variables
      debug:
        msg:
          - "API URL: {{ px_backup_api_url }}"
          - "Token: {{ px_backup_token }}"
          - "Total rules to inspect: {{ rules_inspect | length }}"

    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - rules_inspect is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Inspect rules
      block:
        - name: Get rule details
          rule:
            operation: INSPECT_ONE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            org_id: "{{ org_id | default('default') }}"
          register: inspect_result
          loop: "{{ rules_inspect }}"
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to inspect rules: {{ inspect_result.results | selectattr('failed', 'true') | map(attribute='msg') | list }}"
          when: inspect_result is defined and inspect_result.results is defined

        - name: Fail with error message
          fail:
            msg: "Failed to inspect rules. See above for details."

    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ inspect_result }}"
        output_filename_prefix: "rule_inspect"
      when: output_config.enabled | default(false)