---
- name: Update PX-Backup rule ownership
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/rule/update_ownership.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - rule_ownership_updates is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Update rules ownership
      block:
        - name: Update rule ownership
          rule:
            operation: UPDATE_OWNERSHIP
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id | default('default') }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            ownership: "{{ item.ownership }}"
          loop: "{{ rule_ownership_updates }}"
          register: ownership_result
          loop_control:
            label: "{{ item.name }}"


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ ownership_result }}"
        output_filename_prefix: "rule_update_ownership"
      when: output_config.enabled | default(false)