---
- name: Configure PX-Backup Locations
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup_location/create.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - backup_locations is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Create backup locations
      block:
        - name: Create backup location
          backup_location:
            operation: CREATE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            org_id: "{{ org_id | default('default') }}"
            location_type: "{{ item.location_type }}"
            path: "{{ item.path }}"
            encryption_key: "{{ item.encryption_key | default(omit) }}"
            cloud_credential_ref: "{{ item.cloud_credential_ref | default(omit) }}"
            validate_cloud_credential: "{{ item.validate_cloud_credential | default(true) }}"
            object_lock_enabled: "{{ item.object_lock_enabled | default(false) }}"
            s3_config: "{{ item.s3_config | default(omit) }}"
            google_config: "{{ item.google_config | default(omit) }}"
            azure_config: "{{ item.azure_config | default(omit) }}"
            nfs_config: "{{ item.nfs_config | default(omit) }}"
            validate_certs: "{{ item.validate_certs | default(true) }}"
          loop: "{{ backup_locations }}"
          register: backup_location_result
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to create backup location: {{ backup_location_result.results | selectattr('failed', 'true') | map(attribute='msg') | list }}"
          when: backup_location_result is defined and backup_location_result.results is defined

        - name: Fail with error message
          fail:
            msg: "Failed to create backup locations. See above for details."


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ backup_location_result }}"
        output_filename_prefix: "backup_location_create"
      when: output_config.enabled | default(false)
