---
- name: List all PX-Backup backup locations
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir}}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup_location/enumerate.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
        fail_msg: "Required variables px_backup_api_url must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Backup Location Enumerate call
      backup_location:
        operation: INSPECT_ALL
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        org_id: "{{ org_id | default('default') }}"
