---
- name: Update PX-Backup backup location ownership
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup_location/update_ownership.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - px_backup_token is defined
          - backup_ownership_updates is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Update backup locations ownership
      block:
        - name: Update backup location ownership
          backup_location:
            operation: UPDATE_OWNERSHIP
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id | default('default') }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            location_type: "{{ item.location_type }}"
            cloud_credential_name: "{{ item.cloud_credential_name | default(omit) }}"
            cloud_credential_uid: "{{ item.cloud_credential_uid | default(omit) }}"
            s3_config: "{{ item.s3_config | default(omit) }}"
            google_config: "{{ item.google_config | default(omit) }}"
            azure_config: "{{ item.azure_config | default(omit) }}"
            nfs_config: "{{ item.nfs_config | default(omit) }}"
            ownership: "{{ item.ownership }}"
          loop: "{{ backup_ownership_updates }}"
          register: ownership_result
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to update ownership: {{ ownership_result.results | selectattr('failed', 'true') | map(attribute='msg') | list }}"
          when: ownership_result is defined and ownership_result.results is defined

        - name: Fail with error message
          fail:
            msg: "Failed to update backup location ownership. See above for details."

    - name: Display update results
      debug:
        msg: 
          - "Successfully updated ownership for backup locations:"
          - "Updated locations: {{ ownership_result.results | map(attribute='item.name') | list }}"
          - "Changed status: {{ ownership_result.results | map(attribute='changed') | list }}"
      when: 
        - ownership_result is defined 
        - ownership_result.results is defined
        - (ownership_result.results | selectattr('failed', 'defined') | selectattr('failed', 'true') | list | length) == 0