---
- name: Update PX-Backup Backup Locations
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup_location/update.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - px_backup_token is defined
          - backup_locations_update is defined
        fail_msg: "Required variables must be defined"

    - name: Get current timestamp
      set_fact:
        current_timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

  tasks:
    - name: Backup and update locations
      block:
        - name: Get current configurations
          backup_location:
            operation: INSPECT_ONE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            org_id: "{{ org_id | default('default') }}"
            include_secrets: "{{ item.include_secrets | default('false') }}"
            validate_certs: "{{ validate_certs }}"
          register: current_configs
          loop: "{{ backup_locations_update }}"
          loop_control:
            label: "{{ item.name }}"

        - name: Backup current configurations
          copy:
            content: "{{ item }}"
            dest: "/tmp/backup_location_{{ item.item.name }}_{{ current_timestamp }}.json"
          loop: "{{ current_configs.results }}"
          loop_control:
            label: "{{ item.item.name }}"
          when: backup_configs | bool

        - name: Update backup locations
          backup_location:
            operation: UPDATE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id | default('default') }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            location_type: "{{ item.location_type }}"
            path: "{{ item.path }}"
            cloud_credential_ref: "{{ item.cloud_credential_ref | default(omit) }}"
            validate_cloud_credential: "{{ item.validate_cloud_credential | default(true) }}"
            object_lock_enabled: "{{ item.object_lock_enabled | default(false) }}"
            labels: "{{ item.labels | default(omit) }}"
            validate_certs: "{{ validate_certs }}"
            s3_config: "{{ item.s3_config | default(omit) }}"
            google_config: "{{ item.google_config | default(omit) }}"
            azure_config: "{{ item.azure_config | default(omit) }}"
            nfs_config: "{{ item.nfs_config | default(omit) }}"
          register: update_result
          loop: "{{ backup_locations_update }}"
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to update backup locations: {{ update_result.results | default([]) | selectattr('failed', 'true') | map(attribute='msg') | list }}"

        - name: Fail with error message
          fail:
            msg: "Failed to update backup locations. See above for details."

    - name: Validate updated configurations
      backup_location:
        operation: INSPECT_ONE
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        org_id: "{{ org_id | default('default') }}"
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        validate_certs: "{{ validate_certs }}"
      register: final_validation
      loop: "{{ backup_locations_update }}"
      loop_control:
        label: "{{ item.name }}"
      when: update_result is changed

    - name: Show update results
      debug:
        msg: 
          - "Update Results:"
          - "----------------------------------------"
          - "Location: {{ item.item.name }}"
          - "Configuration Update: {{ 'Success' if item is changed else 'No changes needed' }}"
          - "Location Status: {{ item.backup_location.backup_location_info.status.status | default('Unknown') }}"
          - "Location Status Reason: {{ item.backup_location.backup_location_info.status.reason | default('Unknown') }}"
          - "----------------------------------------"
      loop: "{{ update_result.results }}"
      loop_control:
        label: "{{ item.item.name }}"

    - name: Summarize update operation
      debug:
        msg:
          - "Update Summary:"
          - "Total attempted: {{ update_result.results | length }}"
          - "Successfully updated: {{ update_result.results | selectattr('changed', 'true') | list | length }}"
          - "Failed updates: {{ update_result.results | selectattr('failed', 'defined') | selectattr('failed', 'true') | list | length }}"
          - "Updated locations: {{ update_result.results | selectattr('changed', 'true') | map(attribute='item.name') | list }}"