---
- name: Configure PX-Backup Schedules
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup_schedule/create_vars.yaml"
  
  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Create Backup Schedule
      block:
        - name: Create Backup Schedule
          backup_schedule:
            operation: CREATE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            org_id: "{{ org_id | default('default') }}"
            reclaim_policy: "{{ item.reclaim_policy }}"
            namespaces: "{{ item.namespaces | default(omit) }}"
            label_selectors: "{{ item.label_selectors | default(omit) }}"
            pre_exec_rule: "{{ item.pre_exec_rule | default(omit)}}"
            post_exec_rule: "{{ item.post_exec_rule | default(omit) }}"
            include_resources: "{{ item.include_resources | default(omit) }}"
            csi_snapshot_class_name: "{{ item.csi_snapshot_class_name }}"
            resource_types: "{{ item.resource_types }}"
            schedule_policy_ref: "{{ item.schedule_policy_ref }}"
            backup_location_ref: "{{ item.backup_location_ref }}"
            pre_exec_rule_ref: "{{ item.pre_exec_rule_ref | default(omit) }}"
            post_exec_rule_ref: "{{ item.post_exec_rule_ref | default(omit) }}"
            backup_type: "{{ item.backup_type }}"
            ns_label_selectors: "{{ item.ns_label_selectors | default(omit) }}"
            cluster_ref: "{{ item.cluster_ref }}"
            backup_object_type: "{{ item.backup_object_type }}"
            skip_vm_auto_exec_rules: "{{ item.skip_vm_auto_exec_rules | default(omit) }}"
            volume_snapshot_class_mapping: "{{ item.volume_snapshot_class_mapping | default(omit) }}"
            direct_kdmp: "{{ item.direct_kdmp }}"
            owner: "admin"
            exclude_resource_types: "{{ item.exclude_resource_types | default(omit) }}"
            labels: "{{ item.labels | default(omit) }}"
          loop: "{{ backup_schedules }}"
          register: backup_result
          loop_control:
            label: "{{ item.name }}"

    # - name: List Add Cloud Credentials
    #   backup_schedule:
    #     operation: INSPECT_ONE
    #     api_url: "{{ px_backup_api_url }}"
    #     token: "{{ px_backup_token }}"
    #     org_id: "{{ org_id }}"
    #     uid: "5ef3cfc7-3f01-4896-a8e0-201d96864205"
    #     name: "kopia"



