---
- name: Configure PX-Backup Schedules
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
  
  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Delete  Backup Schedule
      backup_schedule:
        operation: DELETE
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        org_id: "{{ org_id }}"
        uid: "f7152020"
        name: "schedule-name"
        # SSL Certificate Parameters
        ssl_config: "{{ ssl_config.px_backup | default({}) }}"
      register: delete_result


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ delete_result }}"
        output_filename_prefix: "backup_schedule_delete"
      when: output_config.enabled | default(false)