---
- name: Configure PX-Backup Schedules
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
  
  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - pxcentral_auth_url is defined
          - pxcentral_client_id is defined
          - pxcentral_username is defined
          - pxcentral_password is defined
        fail_msg: "Required variables must be defined"
  tasks:
    - name: Request bearer token
      auth:
        auth_url: "{{ pxcentral_auth_url }}"
        client_id: "{{ pxcentral_client_id }}"
        username: "{{ pxcentral_username }}"
        password: "{{ pxcentral_password }}"
        token_duration: "{{ token_duration }}"
      register: token_response
      check_mode: no

    - name: List All Backup Schedule
      backup_schedule:
        operation: INSPECT_ALL
        api_url: "{{ px_backup_api_url }}"
        token: "{{ token_response.access_token }}"
        org_id: "{{ org_id }}"
        backup_location_ref:
          name: "s3-backup-1"
          uid: "0af0ae2b-6259-4d1a-a3fc-8e40fe229cb6"
        # enumerate_options:
        #   backup_object_type: "VirtualMachine"
        #   time_range:
        #     start_time:
        #     end_time: