---
- name: Configure PX-Backup Schedules
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup_schedule/enumerate_vars.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - org_id is defined
        fail_msg: "Required variables must be defined"
  
  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
      
    - name: List All Backup Schedule
      backup_schedule:
        operation: INSPECT_ALL
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        org_id: "{{ org_id }}"
        enumerate_options:
          cluster_name_filter: "{{ enumerate_options.cluster_name_filter | default(omit) }}"
          cluster_uid_filter: "{{ enumerate_options.cluster_uid_filter | default(omit) }}"
          backup_object_type: "{{ enumerate_options.backup_object_type | default(omit) }}"
      register: backup_schedule_result

    - name: Display backup schedule list summary
      debug:
        msg: 
          - "Total backup schedules found: {{ backup_schedule_result.backups | length }}"
          - "Clusters with backup schedules: {{ backup_schedule_result.backups | map(attribute='backup_info.cluster') | unique | sort | list }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to enumerate backup schedules: {{ backup_schedule_result.msg if backup_schedule_result.msg is defined else 'Unknown error occurred' }}"
          when: backup_schedule_result is defined

        - name: Fail with error message
          fail:
            msg: "Failed to enumerate backup schedules. See above for details."

