---
- name: Configure PX-Backup Schedules
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
  
  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - pxcentral_auth_url is defined
          - pxcentral_client_id is defined
          - pxcentral_username is defined
          - pxcentral_password is defined
        fail_msg: "Required variables must be defined"
  tasks:
    - name: Request bearer token
      auth:
        auth_url: "{{ pxcentral_auth_url }}"
        client_id: "{{ pxcentral_client_id }}"
        username: "{{ pxcentral_username }}"
        password: "{{ pxcentral_password }}"
        token_duration: "{{ token_duration }}"
      register: token_response
      check_mode: no

    - name: List  Backup Schedule
      backup_schedule:
        operation: INSPECT_ONE
        api_url: "{{ px_backup_api_url }}"
        token: "{{ token_response.access_token }}"
        org_id: "{{ org_id }}"
        uid: "092c9ac5-fe55-4eb5-b7c5-23d45eb0a95e"
        name: "bs-1"




