---
- name: Update PX-Backup Backup Schedules
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup_schedule/update_vars.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - backup_schedules_update is defined
        fail_msg: "Required variables must be defined"

    - name: Get current timestamp
      set_fact:
        current_timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Backup and update schedules
      block:
        - name: Update backup schedules
          backup_schedule:
            operation: UPDATE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id | default('default') }}"
            name: "{{ item.name  | default(omit) }}"
            uid: "{{ item.uid | default(omit) }}"
            suspend: "{{ item.suspend }}"
            cluster_ref: "{{ item.cluster_ref | default(omit) }}"
            backup_object_type: "{{ item.backup_object_type | default({'type': 'All'}) }}"
            schedule_policy_ref: "{{ item.schedule_policy_ref | default(omit) }}"
            backup_location_ref: "{{ item.backup_location_ref | default(omit) }}"
            pre_exec_rule_ref: "{{ item.pre_exec_rule_ref | default(omit) }}"
            post_exec_rule_ref: "{{ item.post_exec_rule_ref | default(omit) }}"
            policy_ref: "{{ item.policy_ref | default(omit) }}"
            volume_resource_only_policy_ref: "{{ item.volume_resource_only_policy_ref | default(omit) }}"
            exclude_objects: "{{ item.exclude_objects | default(omit) }}"
            include_objects: "{{ item.include_objects | default(omit) }}"
            include_filter: "{{ item.include_filter | default(omit) }}"
            exclude_filter: "{{ item.exclude_filter | default(omit) }}"
            cluster_scope: "{{ item.cluster_scope | default(omit) }}"
            labels: "{{ item.labels | default(omit) }}"
            # SSL Certificate Parameters
            ssl_config: "{{ ssl_config.px_backup | default({}) }}"
          register: update_result
          loop: "{{ backup_schedules_update }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to update backup schedules: {{ update_result.results | default([]) | selectattr('failed', 'true') | map(attribute='msg') | list }}"

        - name: Fail with error message
          fail:
            msg: "Failed to update backup schedules. See above for details."

    - name: Show update results
      debug:
        msg: 
          - "Update Results:"
          - "----------------------------------------"
          - "Schedule: {{ item.item }}"
          - "Configuration Update: {{ 'Success' if item is changed else 'No changes needed' }}"
          - "----------------------------------------"
      loop: "{{ update_result.results }}"


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ update_result }}"
        output_filename_prefix: "backup_schedule_update"
      when: output_config.enabled | default(false)