---
- name: Configure PX-Backup cloud credentials
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/cloud_credential/delete_vars.yaml"
  
  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"

    - name: Create Cloud Credentials
      block:
        - name: Create Cloud Credential
          cloud_credential:
            operation: DELETE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            org_id: "{{ org_id | default('default') }}"
            uid: "{{ item.uid }}"
          loop: "{{ cloud_credentials }}"
          register: cloudcred_result
          loop_control:
            label: "{{ item.name }}"


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ cloudcred_result }}"
        output_filename_prefix: "cloud_credential_delete"
      when: output_config.enabled | default(false)