---
- name: List all PX-Backup Cloud Credentials
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir}}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/cloud_credential/enumerate_vars.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
        fail_msg: "Required variables px_backup_api_url must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Cloud Credential Enumerate call
      cloud_credential:
        operation: INSPECT_ALL
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        org_id: "{{ org_id | default('default') }}"
        # SSL Certificate Parameters
        validate_certs: "{{ px_backup_validate_certs | default(true) }}"
        ca_cert: "{{ px_backup_ca_cert | default(omit) }}"
        client_cert: "{{ px_backup_client_cert | default(omit) }}"
        client_key: "{{ px_backup_client_key | default(omit) }}"
      register: cloudcred_result


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ cloudcred_result }}"
        output_filename_prefix: "cloud_credential_enumerate"
      when: output_config.enabled | default(false)