# ansible-collection/examples/backup/enumerate.yaml
---
- name: Enumerate PX-Backup Backups
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup/enumerate.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - org_id is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Enumerate backups
      block:
        - name: Get list of backups
          backup:
            operation: INSPECT_ALL
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id }}"
            # Optional filters
            cluster_name_filter: "{{ cluster_name_filter | default(omit) }}"
            cluster_uid_filter: "{{ cluster_uid_filter | default(omit) }}"
            name_filter: "{{ name_filter | default(omit) }}"
            labels: "{{ labels | default(omit) }}"
            max_objects: "{{ max_objects | default(2) }}"
            include_detailed_resources: "{{ include_detailed_resources | default(false) }}"
            owners: "{{ owners | default(omit) }}"
            backup_object_type: "{{ backup_object_type | default(omit) }}"
            status: "{{ status | default(omit) }}"
            sort_option: "{{ sort_option | default(omit) }}"
            schedule_policy_ref: "{{ schedule_policy_ref | default(omit) }}"
            backup_schedule_ref: "{{ backup_schedule_ref | default(omit) }}"
            validate_certs: "{{ validate_certs | default(true) }}"
          register: backup_result


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ backup_result }}"
        output_filename_prefix: "backup_enumerate"
      when: output_config.enabled | default(false)