# ansible-collection/examples/backup/inspect.yaml
---
- name: Inspect PX-Backup Backup
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - org_id is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Inspect backup
      block:
        - name: Get backup details
          backup:
            operation: INSPECT_ONE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id }}"
            name: "{{ backup_name }}"
            uid: "{{ backup_uid }}"
            validate_certs: "{{ validate_certs | default(true) }}"
          register: backup_result

        # Optional debug output
        - name: Show raw response
          debug:
            msg: "{{ backup_result | to_nice_json }}"
          when: debug_output | default(false)

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to inspect backup: {{ backup_result.msg if backup_result.msg is defined else 'Unknown error occurred' }}"
          when: backup_result is defined

        - name: Fail with error message
          fail:
            msg: "Failed to inspect backup. See above for details."