# ansible-collection/examples/backup/inspect.yaml
---
- name: Inspect PX-Backup Backup
  hosts: localhost
  gather_facts: false

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup/inspect.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - org_id is defined
          - backup_name is defined
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Inspect backup
      block:
        - name: Get backup details
          backup:
            operation: INSPECT_ONE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id }}"
            name: "{{ backup_name }}"
            uid: "{{ backup_uid | default(omit) }}"
            validate_certs: "{{ validate_certs | default(true) }}"
          register: backup_result

        # Optional debug output
        - name: Show raw response
          debug:
            msg: "{{ backup_result | to_nice_json }}"
          when: debug_output | default(true)

    # YAML Display - Using built-in to_yaml filter
        - name: Display as YAML
          vars:
            yaml_data:
              generated: "{{ ansible_date_time.iso8601 }}"
              backup: "{{ backup_result.backup }}"
          debug:
            msg: "{{ yaml_data | to_yaml }}"
