---
# ansible-collection/examples/backup/update_backup_share.yaml
- name: Update PX-Backup Share Settings
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/backup/update_backup_share.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - org_id is defined
          - backup_share_updates is defined
        fail_msg: "Required variables must be defined"

    - name: Validate collaborators and groups
      assert:
        that:
          - (item.backup_share.collaborators | default([])) | length > 0 or (item.backup_share.groups | default([])) | length > 0
          - ((item.backup_share.collaborators | default([]) | selectattr('id', 'defined') | selectattr('access', 'defined') | list) | length) == ((item.backup_share.collaborators | default([])) | length)
          - ((item.backup_share.groups | default([]) | selectattr('id', 'defined') | selectattr('access', 'defined') | list) | length) == ((item.backup_share.groups | default([])) | length)
        fail_msg: >
          Validation failed for backup '{{ item.name }}':
          - Collaborators or groups are not defined.
          - Some collaborators or groups are missing required 'id' or 'access' entries.
      loop: "{{ backup_share_updates }}"
      loop_control:
        label: "{{ item.name }}"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Update backup shares
      block:
        - name: Update backup share settings
          backup:
            operation: UPDATE_BACKUP_SHARE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id }}"
            name: "{{ item.name }}"
            uid: "{{ item.uid }}"
            backup_share: "{{ item.backup_share | default({}) }}"
            # SSL Certificate Parameters
            validate_certs: "{{ px_backup_validate_certs | default(true) }}"
            ca_cert: "{{ px_backup_ca_cert | default(omit) }}"
            client_cert: "{{ px_backup_client_cert | default(omit) }}"
            client_key: "{{ px_backup_client_key | default(omit) }}"
          register: share_result
          loop: "{{ backup_share_updates }}"
          loop_control:
            label: "{{ item.name }}"

      rescue:
        - name: Display error details
          debug:
            msg: "Failed to update backup shares: {{ 'One or more items failed' if share_result.results is defined else share_result.msg | default('Unknown error occurred') }}"
          when: share_result is defined

        - name: Fail with error message
          fail:
            msg: "Failed to update backup shares. See above for details."


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ share_result }}"
        output_filename_prefix: "update_backup_share"
      when: output_config.enabled | default(false)

