
---
# Define rules list
rules:
  # Example rule 1
  - name: "test-rule-1"
    validate_certs: true
    labels:
      rule-label: "test-label"
    rules:
      - pod_selector: 
          app: app-1
        actions:
          - value: "command-1"
          - value: "command-2"
            background: false

  # Example rule 2
  - name: "test-rule-2"
    validate_certs: true
    rules:
      - pod_selector:
          app: app-2
        actions:
          - background: true
            run_in_single_pod: true
            value: "command-1"