---
# Backup locations to inspect
rules_inspect:
  - name: "test-rule-1"
    uid: "test-rule-1-uid"

  - name: "test-rule-2"
    uid: "test-rule-2-uid"

# Global inspect configuration
validate_certs: false