---
- name: Configure PX-Backup restores
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/restore/create.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - restores is defined
          - restores | length > 0
        fail_msg: "Required variables must be defined"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Create restores
      block:
        - name: Create restore
          restore:
            operation: CREATE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            name: "{{ item.name }}"
            org_id: "{{ org_id | default('default') }}"
            backup_ref: "{{ item.backup_ref }}"
            cluster_ref: "{{ item.cluster_ref }}"
            namespace_mapping: "{{ item.namespace_mapping | default({}) }}"
            storage_class_mapping: "{{ item.storage_class_mapping | default({}) }}"
            include_resources: "{{ item.include_resources | default(omit) }}"
            validate_certs: "{{ item.validate_certs | default(true) }}"
            replace_policy: "{{ item.replace_policy | default('Retain') }}"
            rancher_project_mapping: "{{ rancher_project_mapping | default(omit) }}"
            rancher_project_name_mapping: "{{ rancher_project_name_mapping | default(omit) }}"
            cluster: "{{ item.cluster if item.cluster is defined else item.cluster_ref.name }}"
          loop: "{{ restores }}"
          register: restore_result
          loop_control:
            label: "{{ item.name }}"

    # YAML Display - Using built-in to_yaml filter
        - name: Display as YAML
          vars:
            yaml_data:
              generated: "{{ ansible_date_time.iso8601 }}"
              backup: "{{ restore_result }}"
          debug:
            msg: "{{ yaml_data | to_nice_yaml }}"