---
# ansible-collection/examples/restore/delete.yaml
- name: Delete PX-Backup Restores
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ inventory_dir }}/group_vars/common/all.yaml"
    - "{{ inventory_dir }}/group_vars/restore/delete.yaml"

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - px_backup_api_url is defined
          - org_id is defined
          - restore_deletes is defined
        fail_msg: "Required variables must be defined"

    # Validate restore configurations
    - name: Validate restore configurations
      assert:
        that: 
          - "item.name is defined"
        fail_msg: "Each restore configuration must include 'name'"
      loop: "{{ restore_deletes }}"
      loop_control:
        label: "{{ item.name }}"

  tasks:
    - name: Login and fetch Px-Backup token
      include_tasks: "{{ playbook_dir | dirname }}/auth/auth.yaml"
    - name: Delete restores
      block:
        - name: Delete restore
          restore:
            operation: DELETE
            api_url: "{{ px_backup_api_url }}"
            token: "{{ px_backup_token }}"
            org_id: "{{ org_id }}"
            name: "{{ item.name }}"
            cluster_ref: "{{ item.cluster_ref | default(omit) }}"
            validate_certs: "{{ item.validate_certs | default(true) }}"
          register: delete_result
          loop: "{{ restore_deletes }}"
          loop_control:
            label: "{{ item.name }}"


    # Output configuration: Display the output or save to file
    - name: Handle output
      include_tasks: "{{ playbook_dir | dirname }}/output_handler/main.yaml"
      vars:
        output_data: "{{ delete_result }}"
        output_filename_prefix: "restore_delete"
      when: output_config.enabled | default(false)